{% set name = "lancedb" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v{{ version }}.tar.gz
  sha256: 165a6a8525bf80cd56713e491e4bffadb4b667a6af12e883a03fd70d75db3023

build:
  number: 0
  skip: true  # [py<=38]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - libprotobuf
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.4                       # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.4
    - pip
    - openssl
  run:
    - python
    - deprecation
    - pylance =0.23.0
    - requests >=2.31.0
    - retry >=0.9.2
    - tqdm >=4.27.0
    - pydantic >=1.10
    - attrs >=21.3.0
    - packaging
    - cachetools
    - overrides >=0.7
    - nest-asyncio

test:
  imports:
    - lancedb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
