{% set name = "lancedb" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v{{ version }}.tar.gz
  sha256: 52646a68839974d5d5bc3d5564d576c0b089b1d0691b3e6f6ab9e7d7b74ad787
  patches:
    - ratelimiter.patch

build:
  script: cd python; {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<=38]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - protobuf
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.4                       # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.4
    - pip
  run:
    - python
    - deprecation
    - pylance ==0.13.0
    # # ratelimiter package doesn't work on 3.11
    # https://github.com/lancedb/lancedb/blob/main/python/python/tests/test_embeddings.py#L39
    - ratelimiter >=1.0,<2.dev0  # [py<311]
    - requests >=2.31.0
    - retry >=0.9.2
    - tqdm >=4.27.0
    - pydantic >=1.10
    - attrs >=21.3.0
    - packaging
    - cachetools
    - overrides >=0.7

test:
  imports:
    - lancedb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
