{% set name = "lancedb" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v{{ version }}.tar.gz
  sha256: 9bfd09ccfcae89dedba7c759f1634a34fe45b79d5b5f36e89a2206a71e8e64c3

build:
  number: 0
  skip: true  # [py<=38]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - libprotobuf
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.4                       # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.4
    - pip
    - openssl
  run:
    - aiohttp
    - attr
    - semver >=3.0
    - python
    - deprecation
    - pylance =0.24.0
    - requests >=2.31.0
    - retry
    - tqdm
    - pydantic
    - attrs >=21.3.0
    - packaging
    - cachetools
    - overrides >=0.7
    - nest-asyncio

test:
  imports:
    - lancedb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
