{% set name = "lancedb" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/{{ name }}/archive/refs/tags/python-v{{ version }}.tar.gz
  sha256: 09744899db55bc4a9c3065a33f5065554f657525ec5a1affbbe47b485ef14680

build:
  entry_points:
    - lancedb = lancedb.cli.cli:cli
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - openssl
    - pkgconfig
    - protobuf
  host:
    - python
    - setuptools
    - pip
    - maturin
  run:
    - deprecation
    - numpy
    - pyarrow
    - retry >=0.9.2
    - tqdm >=4.27.0
    - pydantic >=1.10
    - attrs >=21.3.0
    - semver >=3.0
    - cachetools
    - pylance ==0.10.5
    - pyyaml >=6.0
    - click >=8.1.7
    - requests >=2.31.0
    - overrides >=0.7

test:
  imports:
    - lancedb
  commands:
    - lancedb --help

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
