{% set name = "lancedb" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/{{ name }}/archive/refs/tags/python-v{{ version }}.tar.gz
  sha256: dfa9dea132b5d3a55b24526622bd39d099acca4cba482ead021e95ff007a7b12

build:
  number: 0
  skip: True  # [py<39]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - protobuf
  host:
    - python
    - openssl
    - pip
    - maturin >=1.4
  run:
    - python
    - deprecation
    - pylance ==0.12.1
    - requests >=2.31.0
    - retry >=0.9.2
    - tqdm >=4.27.0
    - pydantic >=1.10,<3
    - attrs >=21.3.0
    - packaging
    - cachetools
    - overrides >=0.7
    # not in pyproject.toml but in source
    - pyarrow
    - pyyaml
  run_constrained:
    # https://github.com/lancedb/lancedb/pull/37/files
    - ratelimiter >=1.0,<2

test:
  imports:
    - lancedb

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
