{% set name = "lancedb" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v{{ version }}.tar.gz
  sha256: 6eba63e8286a046de2281cb02af284f28696abfda6c09d6be7ec09994c1e1fb6

build:
  number: 0
  skip: true  # [py<=38]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - libprotobuf
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.4                       # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.4
    - pip
    - openssl
  run:
    - python
    - deprecation
    - pylance =0.19.1
    - requests >=2.31.0
    - retry >=0.9.2
    - tqdm >=4.27.0
    - pydantic >=1.10
    - attrs >=21.3.0
    - packaging
    - cachetools
    - overrides >=0.7

test:
  imports:
    - lancedb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
