schema_version: 1

context:
  name: lancedb
  version: "0.21.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v${{ version }}.tar.gz
  sha256: 0725a1b5d3d80658e55f596ba7dac362c6970b12007ab3af8f91165823563db0

build:
  number: 0
  skip: match(python, "<=3.8")

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - libprotobuf
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: maturin >=1.4
  host:
    - python
    - maturin >=1.4
    - pip
    - openssl
  run:
    - python
    - deprecation
    - pylance =0.24.0
    - requests >=2.31.0
    - retry
    - tqdm
    - pydantic >=1.10
    - attrs >=21.3.0
    - packaging
    - cachetools
    - overrides >=0.7
    - nest-asyncio

tests:
  - python:
      imports:
        - lancedb
      pip_check: true

about:
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/lancedb/lancedb

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
