schema_version: 1

context:
  version: 0.34.0-beta.1

package:
  name: lancedb
  version: ${{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v${{ version }}.tar.gz
  sha256: 6903c63f1ca7f6d20d7f8b5cf70fc72f5a059e8513ded0ce1ec498eba56d9735

build:
  number: 0
  skip: match(python, "<3.10")

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - libprotobuf
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
        - maturin >=1.4
  host:
    - python
    - maturin >=1.4
    - pip
    - openssl
  run:
    - python
    - deprecation
    - tqdm >=4.27.0
    - pydantic >=1.10
    - packaging
    - if: match(python, "<3.12")
      then: overrides >=0.7
    - pylance ==0.19.2-beta.3
    - nest-asyncio >=1.0,<2.dev0
tests:
  - python:
      imports:
        - lancedb
      pip_check: true

about:
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/lancedb/lancedb

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
