schema_version: 1

context:
  version: 0.31.0-beta.10

package:
  name: lancedb
  version: ${{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v${{ version }}.tar.gz
  sha256: f407ff9b93e1147772cfb025f9e42354fa307d20b297524c5ea97a86b4ab2f6c

build:
  number: 0
  skip: match(python, "<3.10")

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - libprotobuf
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
        - maturin >=1.4
  host:
    - python
    - maturin >=1.4
    - pip
    - openssl
  run:
    - python
    - deprecation
    - tqdm >=4.27.0
    - pydantic >=1.10
    - packaging
    - pyarrow >=14
    - if: match(python, "<3.12")
      then: overrides >=0.7
    - numpy
tests:
  - python:
      imports:
        - lancedb
      pip_check: true

about:
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/lancedb/lancedb

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
