github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\  # <- potentially not necessary, but C: tends to have more space (~70 GB) available
      SET_PAGEFILE: "True"
